# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CKYSTemplate' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
      # 异常统计
      pod 'Bugly'
      #网络请求处理多线程框架
      pod 'AFNetworking', '~> 3.1.0'
#      #上下拉刷新
#      pod 'MJRefresh'
#      #autoLyout 布局
      pod 'Masonry', '~> 1.1.0’
#      #UI costum self
      pod 'UIButtonUnit'
#      #数据解析
#      pod 'MJExtension'
#      #地图
#      pod 'BaiduMapKit', '~>3.4.4'
#      #阿里云存储
#      pod 'AliyunOSSiOS'
#      #推送
#      pod 'JPush'
#      #图片异步加载
#      pod 'SDWebImage'
#      #融云 即时通讯
#      pod 'RongCloudIM'

end
